apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: kubserv
  labels:
    app: kubserv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubserv
  template:
    metadata:
      labels:
        app: kubserv 
    spec:
      containers:
      - name: kubserv
        image: kristgo/kubserv:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080    
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.3"
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: kubserv
  labels:
    app: kubserv
spec: 
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: kubserv
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     ingressclass.kubernetes.io/is-default-class: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: kubserv.test
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: kubserv
#             port:
#               number: 80