apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: kubserv             # Unique name of the Kubernetes resource
  labels:
    app: kubserv
spec:
  replicas: 2                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: kubserv          # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: kubserv 
    spec:
      containers:
      - name: kubserv
        image: kristgo/kubserv:0.0.5 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080  # Should match the port number that the Go application listens on  
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080      
        resources:
          limits:
            memory: 600Mi
            cpu: 400m
          requests:
            memory: 200Mi
            cpu: 100m
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: kubserv     # Unique name of the resource
  labels:
    app: kubserv
spec:
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: kubserv            # Map any pod with label `app=go-redis-app` to this service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingressclass.kubernetes.io/is-default-class: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # ingressClassName: nginx
  rules:
  - host: kubserv.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubserv
            port:
              number: 80